language: go
go:
  - 1.9.x
env:
  DEFINE_PATH="scripts"
install:
  - go get github.com/kjoedicker/define
  - go get -v .
  - go get -u golang.org/x/lint/golint
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go build -v .
  - chmod +x setup.sh 
  - /scripts/setup.sh
  - go test -v .
